import { jsPDF } from "jspdf";
import type { MatrixAsset, Media } from '@/types';

export const ReportService = {
    /**
     * Generates a PDF report of selected Matrix Assets.
     * Returns a Blob that can be uploaded to Firebase Storage.
     */
    generateAssetReport: async (assets: (MatrixAsset | Media)[], title: string, userName: string): Promise<Blob> => {
        // Initialize PDF (Portrait, Millimeters, A4)
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;
        
        // --- HEADER & TITLE ---
        doc.setFont("times", "bold");
        doc.setFontSize(22);
        doc.text("ARCHIVIST REPORT", pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(`Subject: ${title}`, 20, 35);
        doc.text(`Prepared for: ${userName}`, 20, 42);
        doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 49);

        doc.setLineWidth(0.5);
        doc.setDrawColor(150);
        doc.line(20, 55, pageWidth - 20, 55);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Total Artifacts Found: ${assets.length}`, 20, 62);

        // --- ASSET LIST ---
        let yPos = 75;
        const margin = 20;
        const itemHeight = 35; 
        
        // Loop through assets
        for (let i = 0; i < assets.length; i++) {
            const asset = assets[i];
            
            // Check for Page Break
            if (yPos + itemHeight > pageHeight - 20) {
                doc.addPage();
                yPos = 20; // Reset to top
            }

            // 1. Thumbnail Placeholder
            // (Note: Real image embedding requires fetching Blob/Base64 which is heavy. 
            // We use a visual placeholder for the text report to keep it fast.)
            doc.setDrawColor(200);
            doc.setFillColor(245, 245, 245);
            doc.rect(margin, yPos, 25, 25, "FD"); // Filled Draw
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(asset.fileType.split('/')[1].toUpperCase(), margin + 12.5, yPos + 15, { align: "center" });

            // 2. Metadata
            doc.setTextColor(0);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            // Title or Filename
            const displayTitle = asset.title || asset.originalName || "Untitled Artifact";
            doc.text(displayTitle, margin + 30, yPos + 5);

            // 3. Details
            doc.setFont("helvetica", "normal");
            doc.setFontSize(9);
            doc.setTextColor(80);
            
            // [ZEN FIX] Handle multiple date fields
            const rawDate = asset.logicalDate || 
                           (asset as any).uploadDate || 
                           (asset as any).dateAdded || 
                           new Date();
            const dateStr = new Date(rawDate).toLocaleDateString();
            doc.text(`Date: ${dateStr}`, margin + 30, yPos + 12);
            
            // [ZEN FIX] Safely handle undefined size
            const sizeInBytes = asset.size || 0;
            const sizeStr = (sizeInBytes / 1024).toFixed(1) + " KB";
            doc.text(`Size: ${sizeStr} | Type: ${asset.fileType}`, margin + 30, yPos + 17);

            // 4. Description / Caption
            const desc = asset.caption || asset.description || "No description provided.";
            // Wrap text
            const splitDesc = doc.splitTextToSize(desc, pageWidth - margin - 30 - 20); // Width minus margins and thumb
            
            // Limit description lines to prevent overlap
            const maxLines = 3;
            const finalDesc = splitDesc.length > maxLines ? splitDesc.slice(0, maxLines) : splitDesc;
            
            doc.setTextColor(50);
            doc.text(finalDesc, margin + 30, yPos + 24);

            // Separator
            doc.setDrawColor(240);
            doc.line(margin, yPos + 30, pageWidth - margin, yPos + 30);

            yPos += itemHeight;
        }

        // --- FOOTER ---
        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${totalPages} - Generated by Project Gigi`, pageWidth / 2, pageHeight - 10, { align: "center" });
        }

        return doc.output("blob");
    }
};