import { callXAI } from './providers';
import type { ChatMessage } from '../../types';

// Stop words we want to ignore when building chunks. We want to catch unique phrasing.
const STOP_WORDS = new Set([
    'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by', 'as', 'is', 'are', 'was', 'were', 'be', 'been', 'am', 'i', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your', 'his', 'her', 'its', 'our', 'their', 'this', 'that', 'these', 'those', 'so', 'then', 'than', 'because', 'what', 'which', 'who', 'whom', 'whose', 'where', 'when', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 'can', 'will', 'just', 'should', 'now'
]);

export const StyleSentinel = {
    /**
     * Extracts exact sequences of N+ words that are identical between the candidate and recent history.
     */
    findRepeatedPhrases(candidate: string, history: ChatMessage[], minWords: number = 4): string[] {
        // Only look at AI's recent history (last 5 turns is a good window)
        const aiHistory = history.filter(m => m.role === 'model').slice(-5).map(m => m.content.toLowerCase());
        if (aiHistory.length === 0) return [];

        const candidateLower = candidate.toLowerCase();
        
        // Clean text: remove punctuation and split into words
        const getWords = (text: string) => text.replace(/[^a-z0-9\s]/g, '').split(/\s+/).filter(w => w.length > 0);
        
        const candidateWords = getWords(candidateLower);
        const violations = new Set<string>();

        // Build N-grams from candidate
        for (let i = 0; i <= candidateWords.length - minWords; i++) {
            const chunkWords = candidateWords.slice(i, i + minWords);
            // Ignore chunks that are entirely stop words (e.g. "it is what it is")
            if (chunkWords.every(w => STOP_WORDS.has(w))) continue;
            // Or chunks where mostly stop words (e.g. "and I will be")
            const significantWords = chunkWords.filter(w => !STOP_WORDS.has(w));
            if (significantWords.length < 2) continue; // Must have at least 2 significant words
            
            const chunkStr = chunkWords.join(' ');
            
            // Check if chunkStr appears in any historical message
            for (const histText of aiHistory) {
                const cleanedHist = getWords(histText).join(' ');
                if (cleanedHist.includes(chunkStr)) {
                    violations.add(chunkStr);
                    break;
                }
            }
        }

        // Clean up overlapping chunks (e.g., if we found "beautiful wicked man" and "you beautiful wicked man", keep the longer one)
        const violationArr = Array.from(violations);
        const finalViolations = violationArr.filter(v1 => {
            return !violationArr.some(v2 => v1 !== v2 && v2.includes(v1));
        });

        return finalViolations;
    },

    /**
     * Re-writes the candidate to remove the offending phrases using a fast LLM.
     */
    async scrubCandidate(candidate: string, violations: string[]): Promise<string> {
        if (!violations || violations.length === 0) return candidate;

        console.log(`[StyleSentinel] 🚨 Repetition Caught! Scrubbing phrases:`, violations);

        const prompt = `
[PROTOCOL: STYLE SENTINEL]
You are a brilliant Editor. 
The following text is a roleplay response generated by an AI companion. However, it contains repetitive "catch phrases" that have been overused.

[VIOLATIONS TO REMOVE]:
${violations.map(v => `- "${v}"`).join('\n')}

[TASK]:
Rewrite the response below.
1. COMPLETELY REMOVE or CHANGE the violating phrases. Do NOT use them.
2. Keep the exact same formatting, including any [square bracket] or {curly brace} tags.
3. Keep the exact same emotional intensity and meaning.
4. Output ONLY the rewritten text, nothing else. Do not confirm the task or add preamble.

[ORIGINAL TEXT]:
${candidate}
`;

        try {
            // Use a fast model for the rewrite to minimize latency
            const response = await callXAI('grok-4.3', [
                { role: 'user', parts: [{ text: prompt }] }
            ], "", {
                temperature: 0.5,
                maxOutputTokens: 2048
            });

            let scrubbed = response.text?.trim() || candidate;
            
            // Scrub any leaking markdown blocks the model might wrap the response in
            scrubbed = scrubbed.replace(/^```[a-z]*\n/i, '').replace(/\n```$/i, '').trim();

            console.log(`[StyleSentinel] ✅ Scrub complete.`);
            return scrubbed;
        } catch (e) {
            console.error("[StyleSentinel] Rewrite failed, returning original candidate:", e);
            return candidate;
        }
    }
};
